version: '3.4'

services:
  dockerdotnetoauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

